# Generated by Django 4.0.4 on 2022-05-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_released',
            field=models.DateField(),
        ),
    ]
